name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy the Docker image
      run: |
        cd webtest
        sudo docker stop flutterweb || true
        sudo docker rm flutterweb || true
        sudo docker rmi flutterwebpage:latest || true
        sudo docker build -t flutterwebpage:latest -f Dockerfile .
        sudo docker run -d -p 80:80 --name flutterweb flutterwebpage:latest
