name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on:  self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: deploy the Docker image
      run: cd webtest && docker build -t flutterwebpage:$(date +%s) -f Dockerfile . && docker run  -p 80:80 flutterwebpage:$(date +%s)
